import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/components/providers/QueryProvider';
import { AuthInitializer } from '@/components/auth/AuthInitializer';
import { Toaster } from '@/components/ui/sonner';
import AppShell from '@/components/layout/AppShell';
import { usePathname } from 'next/navigation';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: '/coffee.jpeg' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname =
    typeof window !== 'undefined' ? window.location.pathname : '';
  const isAdmin = pathname.startsWith('/admin');

  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Toaster
          visibleToasts={1}
          toastOptions={{
            className: [
              'flex items-center justify-center text-center',
              'text-base font-bold py-3 px-6 rounded-2xl shadow-2xl z-[99999]',
              'bg-black/90 text-white border-4 border-yellow-400',
            ].join(' '),
            duration: 1500,
          }}
          style={{
            position: 'fixed',
            left: '50%',
            top: '10%',
            transform: 'translate(-50%, -50%)',
            pointerEvents: 'none',
          }}
        />
        <QueryProvider>
          {/* admin 경로가 아닐 때만 AuthInitializer 렌더 */}
          {!isAdmin && <AuthInitializer />}
          <AppShell>{children}</AppShell>
        </QueryProvider>
      </body>
    </html>
  );
}
