name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      
      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install
      
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test || true
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew

      - name: Build and test backend
        working-directory: ./backend
        run: ./gradlew clean build
